#!/usr/bin/env python
 
import sys, time
from mpd_box.daemon import Daemon
from mpd_box.core.management import execute_from_command_line
 
if __name__ == "__main__":
    daemon = Daemon('/tmp/mpd-box.pid')
    if len(sys.argv) >= 2:
        if 'start' == sys.argv[1]:
            if len(sys.argv) == 2:
                execute_from_command_line(sys.argv)
            else:
                if '--daemon' == sys.argv[2] or '--daemonize' == sys.argv[2]:
                    daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
